// Code generated by protoc-gen-go.
// source: myProto.proto
// DO NOT EDIT!

/*
Package playground is a generated protocol buffer package.

It is generated from these files:
	myProto.proto

It has these top-level messages:
	CheckProto
*/
package playground

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckProto struct {
	Id     int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=Status" json:"Status,omitempty"`
	Table  string `protobuf:"bytes,3,opt,name=Table" json:"Table,omitempty"`
	Name   string `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
	Items  string `protobuf:"bytes,5,opt,name=Items" json:"Items,omitempty"`
}

func (m *CheckProto) Reset()                    { *m = CheckProto{} }
func (m *CheckProto) String() string            { return proto.CompactTextString(m) }
func (*CheckProto) ProtoMessage()               {}
func (*CheckProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CheckProto) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CheckProto) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CheckProto) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *CheckProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckProto) GetItems() string {
	if m != nil {
		return m.Items
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckProto)(nil), "playground.CheckProto")
}

func init() { proto.RegisterFile("myProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xad, 0x0c, 0x28,
	0xca, 0x2f, 0xc9, 0xd7, 0x2b, 0x00, 0x91, 0x42, 0x5c, 0x05, 0x39, 0x89, 0x95, 0xe9, 0x45, 0xf9,
	0xa5, 0x79, 0x29, 0x4a, 0x25, 0x5c, 0x5c, 0xce, 0x19, 0xa9, 0xc9, 0xd9, 0x60, 0x79, 0x21, 0x3e,
	0x2e, 0x26, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x26, 0xcf, 0x14, 0x21, 0x31,
	0x2e, 0xb6, 0xe0, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28,
	0x4f, 0x48, 0x84, 0x8b, 0x35, 0x24, 0x31, 0x29, 0x27, 0x55, 0x82, 0x19, 0x2c, 0x0c, 0xe1, 0x08,
	0x09, 0x71, 0xb1, 0xf8, 0x25, 0xe6, 0xa6, 0x4a, 0xb0, 0x80, 0x05, 0xc1, 0x6c, 0x90, 0x4a, 0xcf,
	0x92, 0xd4, 0xdc, 0x62, 0x09, 0x56, 0x88, 0x4a, 0x30, 0x27, 0x89, 0x0d, 0xec, 0x10, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xcd, 0x4a, 0xf5, 0x99, 0x00, 0x00, 0x00,
}
