package main

import (
	"fmt"
)

/*

Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

const p1 int = 4000000

func main() {
	i := 0
	j := 1
	result := 0
	evenResults := 0
	for result < p1 {
		result = i + j
		i = j
		j = result
		fmt.Println(result)
		if result%2 == 0 {
			evenResults += result
		}

	}

	fmt.Println("Even results summed = ", evenResults)
}
